### ISSUE TITLE
Build Containers on a nightly basis

### ISSUE THREAD

**Issue by PacoVK** [keycloak/keycloak-containers#338]
### Description

Currently the official Images are built once and published via Dockerhub and Quay.io. The scan reports suggest that the images are safe however this only represents the status at the time of publishing the containers. At the time of writing the latest version 15.0.2 passes scan [reports](https://quay.io/repository/keycloak/keycloak?tab=tags) but a newer scan report issues several vulnerabilities:
MEDIUM: 30
LOW: 12
HIGH: 1
All are coming from the underlying base OS image. A nighly build will probably fix this. Same approach is implemented for the [Bitnami version of Keycloak](https://hub.docker.com/r/bitnami/keycloak/tags) 
Is there any reason that prevents from having a nightly build cycle for Keycloak container?

**Comment by stianst** [comment]
Won't building every night result in a new image that people have to download? Would be much better to rather automate it based on scanning, and have it rebuilt if needed.

Quay used to refresh the scan regularly and not just at the time of writing. Not sure if they've stopped that, or if they simply don't catch all the CVEs. In either case we are looking at improving on how we scan containers, to have a better solution, that we can then plug-in to delivering re-built images quicker.

**Comment by stianst** [comment]
@abstractj FIY

**Comment by PacoVK** [comment]
Building nightly will download the changed layers of course, containing the fixes. The same you would patch your systems you propably need to redeploy the new container or leave as it is at own risk. However from a production perspective it is crucial to contain a stable and safe image, rather than worrying about download times. 
We use AWS ECR scan as a resource which uses the clairDB as CVE DB source [see](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning.html) 
Maybe a good compromize solution is as you suggested to build only if there are findings. This may require quay.io to nightly scan the image for CVEs.

**Comment by abstractj** [comment]
@stianst one idea to that is to introduce a GH action to run daily (https://github.com/marketplace/actions/aqua-security-trivy), so we can check if there are any critical CVE in the `latest` tag. If Trivy reports a critical/high CVE, we should be able to trigger a new build on quay.io and override the latest tag.

**Comment by stianst** [comment]
With Keycloak 20 the WildFly based distribution is no longer supported. For the newer Quarkus distribution of Keycloak, check out the [new documentation](https://www.keycloak.org/server/containers), or the [updated container sources](https://github.com/keycloak/keycloak/tree/main/quarkus/container).
