### ISSUE TITLE
External JAR files in containered mode

### ISSUE THREAD

**Issue by masoud-moghini** [keycloak/keycloak-containers#342]
### Description

Its quite often that administrators want to provide keycloak with some customized implementation of some feature , the most common is 2FA  with SMS .
in non-containered environment , we act as [how-to-deploy-a-keycloaks-spi-project-using-the-keycloak-deployer-deploy](https://stackoverflow.com/a/53435191/4824894)
but I launched my keycloak , using docker-composed mode . are there any solutions to add custom jar files to IS  using dockerized version ?

**Comment by pgbezerra** [comment]
You can mount a volume with your jars.
If you use operator is even simpler: https://www.keycloak.org/docs/latest/server_installation/index.html#_operator-extensions
