### ISSUE TITLE
Keycloack 15.0.2 Docker cannot run

### ISSUE THREAD

**Issue by donhuvy** [keycloak/keycloak-containers#343]
### Describe the bug

Keycloack 15.0.2 Docker cannot run

### Version

15.0.2

### Expected behavior

Run success at http://localhost:8080/auth/admin

### Actual behavior

return nothing

![image](https://user-images.githubusercontent.com/1328316/144432784-3a8f89d9-4517-4258-b88d-a81c2c413bbb.png)

### How to Reproduce?

```
docker run -p 8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin quay.io/keycloak/keycloak:15.0.2
````

go to http://localhost:8080/auth/admin

### Anything else?

go to http://127.0.0.1:9990/ return nothing

**Comment by Angelinsky7** [comment]
Hello,

i've got the same issue with latest and 16.1.0.
it's impossible to exit the container without crashing it.
I only have `Added 'admin' to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json', restart server to load user
-b 0.0.0.0` in the log (event with  -e KEYCLOAK_LOGLEVEL=DEBUG)
tested on Window10, Debian 12 and Ubuntu 20
