### ISSUE TITLE
Missing Tag on hub.docker.com

### ISSUE THREAD

**Issue by FloSeidel** [keycloak/keycloak-containers#345]
### Describe the bug

This projects latest release seems to be 15.1.0 (4 days ago). [Docker Hub](https://hub.docker.com/r/jboss/keycloak/tags?page=1) us missing this version. It's latest Version is 15.0.2 (4 months ago). I'm not sure if that is expected behaviour. I'm sorry if thats the case.

### Version

15.1.0

### Expected behavior

The latest version is available on Docker hub.

### Actual behavior

Missing the latest Release on Docker Hub

**Comment by stianst** [comment]
It's available now
