### ISSUE TITLE
v15.1.1 is missing on hub.docker.com

### ISSUE THREAD

**Issue by MrDeerly** [keycloak/keycloak-containers#349]
### Describe the bug

Hey,

the latest release is sadly missing on dockerhub. Please make sure to push it, so the installations can be updated.

Thanks!

### Version

v15.1.1

### Expected behavior

v15.1.1 is available on dockerhub

### Actual behavior

v15.1.1 isn't available on dockerhub

### How to Reproduce?

https://hub.docker.com/r/jboss/keycloak/tags

**Comment by jangaraj** [comment]
Main repository is [Quay](https://quay.io/repository/keycloak/keycloak?tab=info). It looks like `15.1.1` build is hanging there (triggered 5 hours ago). Maybe @stianst can check a build status. Let's see status of recent `16.0.0` release:
![image](https://user-images.githubusercontent.com/1182932/146572407-59da982c-c535-43a3-996f-e089cf589516.png)

**Comment by jonathanvila** [comment]
Hi @MrDeerly and @jangaraj , we are investigating the issue. Apologies for the inconvenience.
Something on the Quary side apparently.
Will keep you posted.

**Comment by jonathanvila** [comment]
Meanwhile you can set RELATED_IMAGE_KEYCLOAK in the Operator env vars with the value of the 15.1.0 image.

In the operator yaml : 
                      - name: OPERATOR_NAME
                        value: keycloak-operator
                      - name: RELATED_IMAGE_KEYCLOAK     <-----------
                        value: 'quay.io/keycloak/keycloak:15.1.0'

**Comment by stianst** [comment]
Quay auto builds didn't work for some reason. Images are pushed manually for now.

**Comment by Morl99** [comment]
I am looking for the latest images, have you actually pushed them manually? I cannot find 16.0.0 nor 15.1.1.

**Comment by Morl99** [comment]
I can confirm that the tags up until 16.0.0 now look fine, thanks. 
The newly created 16.1.0 has the same issues though.

**Comment by stianst** [comment]
All the tags should be fine now
