### ISSUE TITLE
Repeated permission in standalone*.xml

### ISSUE THREAD

**Issue by daurrutia** [keycloak/keycloak-containers#351]
### Describe the bug

The line `<permission class-name="org.jboss.ejb.client.RemoteEJBPermission" module="org.jboss.ejb-client"/>` seems to be repeated under the `default-permissions` `permission-set` section of the standalone XML files.

### Version

15.1.0

### Expected behavior

A single line, instead of a duplicated line.

### Actual behavior

Duplicated line.

### How to Reproduce?

`docker run -p 8080:8080 jboss/keycloak:15.1.0`

exec into container

`cat /opt/jboss/keycloak/standalone/configuration/standalone-ha.xml | grep ejb-client`

### Anything else?

Thanks for all your work on this project.

**Comment by stianst** [comment]
With Keycloak 20 the WildFly based distribution is no longer supported. For the newer Quarkus distribution of Keycloak, check out the [new documentation](https://www.keycloak.org/server/containers), or the [updated container sources](https://github.com/keycloak/keycloak/tree/main/quarkus/container).
