### ISSUE TITLE
Built in support for SQL Server Integrated Authentication

### ISSUE THREAD

**Issue by amhest** [keycloak/keycloak-containers#358]
### Description

I have SQL Server Integrated Authentication working with Kerberos and Active Directory inside a rootless keycloak container running on podman.   This is the preferred way to connect to SQL Server in production and uses a kerberos user with no username or password property on the JDBC connect string.   Currently my solution wraps and ignores variables in docker-entrypoint.sh and Dockerfile.  I would prefer to modify it directly and can open a PR if this would be erncouraged.  The main issue is that it requires a kinit statement inside the container prior to JVM launch and requires the krb5-workstation dependency.   

The steps outlined below do not work with wildfly so extra work is needed to map the JAAS config into standalone*.xml

(Assumes host is setup for kerberos logins already.  This makes krb5.conf setup and other testing easier)  
1. Include krb-workstation in the image (This is also needed for other kerberos use cases also)
2. Map /etc/krb5.conf from the host to the container
3. Set JAVA_OPTS (or tell user to use this) -Djava.security.auth.login.config=/tmp/keytabs/jaas.conf -Djava.security.krb5.conf=/etc/krb5.conf
4. Set JDBC_PARAMS to include integratedSecurity=true\;authenticationScheme=JavaKerberos 
5. Obtain a keytab file for the SQL Server user principal from an AD admin and reference this from the jaas config
6. This is the kludgy part without enhancement... before starting keycloak, but inside the container, run kinit to initialize and cache the principal so it will be available when the JVM starts.   Today I do this with a custom entryPoint which calls kinit and then invokes docker-entrypoint.sh but would be better to modify the real version of docker-entrypoint.sh to fork on this option.   Also, when using integratedSecurity its not necessary to pass JDBC user and pass to connection string.

**Comment by stianst** [comment]
With Keycloak 20 the WildFly based distribution is no longer supported. For the newer Quarkus distribution of Keycloak, check out the [new documentation](https://www.keycloak.org/server/containers), or the [updated container sources](https://github.com/keycloak/keycloak/tree/main/quarkus/container).
