### ISSUE TITLE
expose ingress path configuration i.e. web-context using environment variable

### ISSUE THREAD

**Issue by armujahid** [keycloak/keycloak-containers#361]
### Description

default subsystem context is `/` i.e. container runs fine if path = / in ingress. To change ingress path to something else like /auth changes are required as mentioned at https://www.keycloak.org/docs/latest/server_installation/#managing-the-subsystem-configuration
`<web-context>auth</web-context>` 

### Motivation

normally every frequently used configuration should be exposed via environment variables to make container easy to use without requiring any change in application config files inside container.

**Comment by armujahid** [comment]
Update: default subsystem context is `/auth` which is apparently working fine with `/auth` ingress route. Still I think there should be an option to change /auth to something else.

**Comment by stianst** [comment]
With Keycloak 20 the WildFly based distribution is no longer supported. For the newer Quarkus distribution of Keycloak, check out the [new documentation](https://www.keycloak.org/server/containers), or the [updated container sources](https://github.com/keycloak/keycloak/tree/main/quarkus/container).
