### ISSUE TITLE
docker-entrypoint.sh config bootstrap idempotency problems lead to crash loops

### ISSUE THREAD

**Issue by bergner** [keycloak/keycloak-containers#364]
### Issue TL;DR

Using docker run -v keycloak_conf:/opt/jboss/keycloak/standalone/configuration causes container to crash on subsequent starts after docker rm because of non-idempotent Wildfly CLI scripts (some of which might be custom injected scripts).

### Proposal TL;DR

Use a flag file named /opt/jboss/keycloak/standalone/configuration/.configured rather than /opt/jboss/configured to make docker-entrypoint.sh more capable of accurately enforcing that scripts only run once when configuration volumes are used.

### Background

docker-entrypoint.sh tries to run lots of scripts (e.g x509.sh, jgroups.sh, autorun.sh) only once to bootstrap configuration. This is done using a flag file called /opt/jboss/configured.

If a docker volume is used for the /opt/jboss/keycloak/standalone/configuration directory (which could be done to drastically speed up starting a container since certificate imports and some other setup steps take quite significant time) several idempotency problems show up and the container cannot be restarted cleanly with docker kill + docker rm + docker run. Using "docker rm is preferred by Redhat Support over docker stop/start" according to https://stackoverflow.com/a/62563081

Since the /opt/jboss/configured file is on ephemeral storage but the configuration is on a volume all the scripts are invoked again by docker-entrypoint.sh on every start of the container, and now all the underlying scripts need to deal with applying changes to configuration that have already been applied.

There are scripts that are not idempotent and cause either errors in the log or outright crashes that lead to repeated crash loops.

### Version

12.0.4, 13.0.1, 16.1.0

### Expected behavior

Using a configuration volume should still allow the container to be stopped, removed, and then started again. If underlying scripts cannot run more than once there needs to be a more thorough guard than the flag file on ephemeral container storage.

I think it would be highly preferable to have guard file(s) alongside the configuration file(s) themselves and still try to enforce some "run only once" logic in docker-entrypoint.sh simply because the container has several extension points for Wildfly CLI scripts to be injected (for example injecting a TCPPING.cli for JGroups discovery or custom Wildfly startup scripts) and if any of these scripts aren't idempotent they would cause problems on subsequent starts of the container.

### Actual behavior

Various Wildfly CLI scripts (e.g. the default JDBC_PING.cli) perform non-idempotent operations, like "/some/wildfly/path:add(...)" without checking if such a node already exists in the configuration.

### How to Reproduce?

The specific problem I have is a bit more complicated but in essence this should be reproducible by injecting a custom Wildfly CLI startup script that adds some node to the configuration or by configuring JDBC_PING. Combine that with a configuration volume. The first startup should work fine. Stopping the docker rm:ing the container and then repeating the docker run command should illustrate the above mentioned idempotency problems. Additional environment variables for database connectivity needs to be provided in accordance with https://hub.docker.com/r/jboss/keycloak/. In my case I was using a separate docker container running Postgresql 13.

### Reproduce option 1: non-idempotent custom Wildfly CLI script

```
cat <<'EOF' > wildfly_startup.cli
embed-server --server-config=standalone-ha.xml
/subsystem=logging/logger=org.keycloak.saml:add(level=TRACE)
stop-embedded-server
EOF
# keycloak_conf is an empty/non-existing volume to begin with
docker run --name keycloak \
    -v keycloak_conf:/opt/jboss/keycloak/standalone/configuration \
    -v wildfly_startup.cli:/opt/jboss/startup-scripts/wildfly_startup.cli \
    -p 8087:8080 -p 8443:8443 \
    -e DB_ADDR=172.17.0.1:5432 -e DB_USER=keycloak -e DB_PASSWORD=secret5432 -e DB_DATABASE=keycloak -e DB_VENDOR=postgres \
    jboss/keycloak:16.1.0
```
Result on second run: Container crashes with this as the final output of the logs.
```
16:45:17,573 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Keycloak 16.1.0 (WildFly Core 18.0.0.Final) started in 1329ms - Started 49 of 79 services (31 services are lazy, passive or on-demand)
The batch failed with the following error: : 
WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:
Step: step-9
Operation: /subsystem=datasources/jdbc-driver=postgresql:add(driver-name=postgresql, driver-module-name=org.postgresql.jdbc, driver-xa-datasource-class-name=org.postgresql.xa.PGXADataSource)
Failure: WFLYCTL0212: Duplicate resource [
    ("subsystem" => "datasources"),
    ("jdbc-driver" => "postgresql")
]

16:45:17,661 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0050: Keycloak 16.1.0 (WildFly Core 18.0.0.Final) stopped in 10ms
Executing cli script: /opt/jboss/startup-scripts/startup_wildfly.cli
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.wildfly.extension.elytron.SSLDefinitions (jar:file:/opt/jboss/keycloak/modules/system/layers/base/org/wildfly/extension/elytron/main/wildfly-elytron-integration-18.0.0.Final.jar!/) to method com.sun.net.ssl.internal.ssl.Provider.isFIPS()
WARNING: Please consider reporting this to the maintainers of org.wildfly.extension.elytron.SSLDefinitions
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
{
    "outcome" => "failed",
    "failure-description" => "WFLYCTL0212: Duplicate resource [
    (\"subsystem\" => \"logging\"),
    (\"logger\" => \"org.keycloak.saml\")
]",
    "rolled-back" => true
}
```

### Reproduce option 2: JDBC_PING.cli is not idempotent and neither are TCPPING etc. examples

Note that this is not a "100% correct" setup of JDBC_PING clustering but it does exhibit the non-idempotent behavior of JDBC_PING.cli causing the container to crash.

```
docker run --name keycloak \
    -v keycloak_conf:/opt/jboss/keycloak/standalone/configuration \
    -e JGROUPS_DISCOVERY_PROTOCOL=JDBC_PING \
    -e JGROUPS_DISCOVERY_PROPERTIES=datasource_jndi_name=java:jboss/datasources/KeycloakDS \
    -p 8087:8080 -p 8443:8443 \
    -e DB_ADDR=172.17.0.1:5432 -e DB_USER=keycloak -e DB_PASSWORD=secret5432 -e DB_DATABASE=keycloak -e DB_VENDOR=postgres \
    jboss/keycloak:16.1.0
```
Result on second run: Container crashes when running JDBC_PING.cli a second time with the following log output at the end:
```
17:08:05,889 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Keycloak 16.1.0 (WildFly Core 18.0.0.Final) started in 1212ms - Started 49 of 79 services (31 services are lazy, passive or on-demand)
The batch failed with the following error: : 
WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:
Step: step-9
Operation: /subsystem=datasources/jdbc-driver=postgresql:add(driver-name=postgresql, driver-module-name=org.postgresql.jdbc, driver-xa-datasource-class-name=org.postgresql.xa.PGXADataSource)
Failure: WFLYCTL0212: Duplicate resource [
    ("subsystem" => "datasources"),
    ("jdbc-driver" => "postgresql")
]

17:08:05,979 INFO  [org.jboss.as] (MSC service thread 1-1) WFLYSRV0050: Keycloak 16.1.0 (WildFly Core 18.0.0.Final) stopped in 10ms
Setting JGroups discovery to JDBC_PING with properties {datasource_jndi_name=>java:jboss/datasources/KeycloakDS}
```

### Workaround

Build a customer version of the image with a revised docker-entrypoint.sh:

```
--- ../../git/keycloak-containers/server/tools/docker-entrypoint.sh	2021-04-15 16:43:58.438152389 +0200
+++ docker-entrypoint.sh	2022-01-13 18:22:21.836870053 +0100
@@ -233,14 +233,12 @@
 echo "========================================================================="
 echo ""
 
-configured_file="/opt/jboss/configured"
+configured_file="/opt/jboss/keycloak/standalone/configuration/.configured"
 if [ ! -e "$configured_file" ]; then
-    touch "$configured_file"
-
+    touch "$configured_file" || echo "FAILED TO WRITE .configured FLAG!"
     if [ "$DB_NAME" != "Embedded H2" ]; then
       /bin/sh /opt/jboss/tools/databases/change-database.sh $DB_VENDOR
     fi
-	
     /opt/jboss/tools/x509.sh
     /opt/jboss/tools/jgroups.sh
     /opt/jboss/tools/infinispan.sh
```

Dockerfile
```
FROM jboss/keycloak:16.1.0
COPY docker-entrypoint.sh /opt/jboss/tools/
```

**Comment by proffalken** [comment]
Ah, I think this could be what's causing https://github.com/keycloak/keycloak/issues/9392 ?

**Comment by stianst** [comment]
With Keycloak 20 the WildFly based distribution is no longer supported. For the newer Quarkus distribution of Keycloak, check out the [new documentation](https://www.keycloak.org/server/containers), or the [updated container sources](https://github.com/keycloak/keycloak/tree/main/quarkus/container).
