### ISSUE TITLE
Add more architectures

### ISSUE THREAD

**Issue by yarons** [keycloak/keycloak-containers#367]
### Description

Running Keycloak on ARM processors (Graviton for example) can reduce hosting costs.

Not to mention Mac M1 and Raspberry Pi.

### Motivation

Save costs for the long term and allow more agile deployment including in ARM based Kubernetes clusters.

### Details

Keycloak is Java based so it should be too complicated to adjust but there are some extra tools such as WildFly that will need some extra care (I'm guessing).

**Comment by intellitour** [comment]
This should be really simple... check this out:

https://hub.docker.com/r/sleighzy/keycloak

**Comment by intellitour** [comment]
This is a duplicate of https://github.com/keycloak/keycloak-containers/issues/341

**Comment by yarons** [comment]
Yup and it already contains the solution :)
