### ISSUE TITLE
Support x509 Client Certificate lookup

### ISSUE THREAD

**Issue by jkroepke** [keycloak/keycloak-containers#369]
### Description

It's a common usecase to that a reverse proxy (e.g. ingress controller) is in the front of keycloak.

It would be great, if the keycloak containers supports Client Certificate lookup out of the box, through an environment variable, like PROXY_ADDRESS_FORWARDING.

### Motivation

Simplify a setup, where client certificates are used for auth.

### Details

https://www.keycloak.org/docs/latest/server_admin/#client-certificate-lookup

**Comment by stianst** [comment]
With Keycloak 20 the WildFly based distribution is no longer supported. For the newer Quarkus distribution of Keycloak, check out the [new documentation](https://www.keycloak.org/server/containers), or the [updated container sources](https://github.com/keycloak/keycloak/tree/main/quarkus/container).
