### ISSUE TITLE
Update default container to Quarkus

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak-containers#370]
### Description

* Rename `server` to `server-legacy`
* Rename `server-x` to `server`

Keycloak Quarkus distribution will be published to:
* `quay.io/keycloak/keycloak:latest`
* `quay.io/keycloak/keycloak:<VERSION>`

Keycloak legacy WildFly distribution will be published to:
* `quay.io/keycloak/keycloak:<VERSION>-legacy`
* `quay.io/keycloak/keycloak:legacy`
* `docker.io/jboss/keycloak:<VERSION>-legacy`
* `docker.io/jboss/keycloak:legacy`

**Comment by ChristianCiach** [comment]
This has been merged over a week ago, but `quay.io/keycloak/keycloak:latest` this references the Wildfly distribution and `quay.io/keycloak/keycloak:server` doesn't exist.

How should people deploy Keycloak today? Is Keycloak-X out of preview and should be used for new project?
