### ISSUE TITLE
17.0.0 does not start

### ISSUE THREAD

**Issue by jdelker** [keycloak/keycloak-containers#379]
### Describe the bug

Docker container keycloak:17.0.0 does not start any more.

Executing `docker run quay.io/keycloak/keycloak:17.0.0` shows usage output:
```
Keycloak - Open Source Identity and Access Management

Find more information at: https://www.keycloak.org/docs/latest

Usage:

kc.sh [OPTIONS] [COMMAND]

Use this command-line tool to manage your Keycloak cluster.
Make sure the command is available on your "PATH" or prefix it with "./" (e.g.:
"./kc.sh") to execute from the current folder.
...
```

### Version

17.0.0

### Expected behavior

Docker container starts keycloak as it did before (<17.0.0).

### Actual behavior

Docker container shows usage info, but does not start.

### How to Reproduce?

Simply run `docker run quay.io/keycloak/keycloak:17.0.0` as documented.

**Comment by stianst** [comment]
Please check release notes and migration guide.

**Comment by jdelker** [comment]
@stianst:
I assume you reference the [Running keycloak in a container](https://www.keycloak.org/server/containers) guide, which basically tells us to always (?) create our own "optimized" container image?

If the non-legacy image provided through this project is not able to start on it's own anymore, I suggest adjusting the [README.md](https://github.com/keycloak/keycloak-containers/blob/main/README.md), because it suggests differently.

**Comment by jdelker** [comment]
Since this is obviously not considered a bug:
Is there a particular reason, why the new 17.0.0 image misses the required "start" option in the "entrypoint"?

**Comment by stianst** [comment]
Updated the readme. It was actually missing the "start-dev" command.

**Comment by stianst** [comment]
@jdelker with the new image you have a choice between "build your own", using "start --auto-build" or for developement purposes using "start-dev". It could potentially make sense to use "start --auto-build" as the default entrypoint, but that would make it a little bit more awkward to do "build your own" or "start-dev" perhaps.

**Comment by maltegrosse** [comment]
@stianst can you please also add/refer to some build instructions for the new containers? seems the folder structure also changed and I need to rebuild a armv7 container
