### ISSUE TITLE
Tag 17.0.0 points to wrong commit with broken Dockerfile

### ISSUE THREAD

**Issue by ioemat** [keycloak/keycloak-containers#382]
### Describe the bug

The `server/Dockerfile` of the [commit tagged with `17.0.0`](https://github.com/keycloak/keycloak-containers/blob/17.0.0/server/Dockerfile) is broken since it does not contain the `-legacy` suffix in the artifact name.

I was about to create a PR to fix it, but realized that this has already been fixed with [455131d5ed24238a6e0e90cd25ffe44f307f140f9](https://github.com/keycloak/keycloak-containers/commit/455131d5ed24238a6e0e90cd25ffe44f307f140f). 

Based on this there is [another commit](https://github.com/keycloak/keycloak-containers/commit/4d7d01e0bb18e4f2b2593150955453d05bb0ede9) that sets the version to 17.0.0.
Looks like this is the commit that should have the tag `17.0.0`.

### Version

17.0.0

### Expected behavior

Tag `17.0.0` points to a commit in the main branch, probably [4d7d01e0bb18e4f2b2593150955453d05bb0ede9](https://github.com/keycloak/keycloak-containers/commit/4d7d01e0bb18e4f2b2593150955453d05bb0ede9)  is the right one.

### Actual behavior

Tag `17.0.0` points to a [commit that is in no branch in the repo](https://github.com/keycloak/keycloak-containers/blob/17.0.0/server/Dockerfile).

The warning "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository." is shown.

The `server/Dockerfile` does not contain the new artifcat name, therefore the file is not usable.

### How to Reproduce?

```
git checkout 17.0.0; 
cat server/Dockerfile
```

**Comment by stianst** [comment]
With Keycloak 20 the WildFly based distribution is no longer supported. For the newer Quarkus distribution of Keycloak, check out the [new documentation](https://www.keycloak.org/server/containers), or the [updated container sources](https://github.com/keycloak/keycloak/tree/main/quarkus/container).
