### ISSUE TITLE
docker-compose-examples do not work w/ KC 17+

### ISSUE THREAD

**Issue by heddn** [keycloak/keycloak-containers#388]
### Describe the bug

The examples use old env variables to connect to the remote postgres (as an example):

```
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
```

They should be something like:
```
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
```

### Version

17+

### Expected behavior

The examples would work with the most recent version of KC

### Actual behavior

Currently, the example do not work with KC17+

**Comment by hookenful** [comment]
environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloakdb
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 1
      KC_FEATURES: token-exchange
      KC_HTTP_ENABLED: true
      KC_PROXY: edge

Please try this. I am on Win10. On M1 I have different.

**Comment by isfong** [comment]
> ### Describe the bug
> The examples use old env variables to connect to the remote postgres (as an example):
> 
> ```
>         DB_VENDOR: POSTGRES
>         DB_ADDR: postgres
>         DB_DATABASE: keycloak
>         DB_USER: keycloak
>         DB_SCHEMA: public
>         DB_PASSWORD: password
>         KEYCLOAK_USER: admin
>         KEYCLOAK_PASSWORD: Pa55w0rd
> ```
> 
> They should be something like:
> 
> ```
>       KC_DB: postgres
>       KC_DB_USERNAME: keycloak
>       KC_DB_PASSWORD: password
>       KC_HOSTNAME: localhost
>       KEYCLOAK_ADMIN: admin
>       KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
> ```
> 
> ### Version
> 17+
> 
> ### Expected behavior
> The examples would work with the most recent version of KC
> 
> ### Actual behavior
> Currently, the example do not work with KC17+
> 
> ### How to Reproduce?
> _No response_
> 
> ### Anything else?
> _No response_

using image  `quay.io/keycloak/keycloak:17.0.1-legacy`   
the 'quay.io/keycloak/keycloak:17.0.1' is builder

**Comment by hypervisorfdi** [comment]
what about this documentation:
https://www.keycloak.org/server/containers

I had to change this line from:

ENV KC_HOSTNAME=localhost:8443

to

ENV KC_HOSTNAME=localhost

**Comment by stianst** [comment]
With Keycloak 20 the WildFly based distribution is no longer supported. For the newer Quarkus distribution of Keycloak, check out the [new documentation](https://www.keycloak.org/server/containers), or the [updated container sources](https://github.com/keycloak/keycloak/tree/main/quarkus/container).
