### ISSUE TITLE
Random generated extension filename contains whitespaces

### ISSUE THREAD

**Issue by twobiers** [keycloak/keycloak-containers#390]
### Description

The extension script downloads extension from a remote resource and sets the filename randomly if it cannot be read from the headers. The command used for this results in a random file name containing whitespaces and especially __leading__ whitespaces.
Possibly this comes from a typo in the `tr -d ""` command which should be `tr -d " "`. However, one could also use `head -c8 /dev/urandom | xxd -p` for that purpose.

There is already a PR ongoing regarding different tweaks on the extension script #316. I will add the suggestions there.

https://github.com/keycloak/keycloak-containers/blob/2391e8699e2aa9718f3c9fb26aec80bde347122a/keycloak-init-container/extensions.sh#L26-L33

### Details

```sh
$  od -N8 -tx1 -An -v /dev/urandom | tr -d ""
 6e d3 0d 52 52 8c d8 4e
$ od -N8 -tx1 -An -v /dev/urandom | tr -d " "
2e1f6c3d514415e6
$ head -c8 /dev/urandom | xxd -p
426b0b2adc9ad3ed
```

**Comment by stianst** [comment]
With Keycloak 20 the WildFly based distribution is no longer supported. For the newer Quarkus distribution of Keycloak, check out the [new documentation](https://www.keycloak.org/server/containers), or the [updated container sources](https://github.com/keycloak/keycloak/tree/main/quarkus/container).
