### ISSUE TITLE
TLSv1.3 support

### ISSUE THREAD

**Issue by abhilashkumar002** [keycloak/keycloak-containers#392]
### Describe the bug

Vulnerable to Logjam attack with TLSv1.2

Run the conatiner.
Go to homepage of keycloak running on protocol https
Go to Developer tools, then Securuty tab
By default its TLSv1.2
How to configute it to run with TLSv1.3?

### Version

all

### How to Reproduce?

version: "2"
services:
  postgresql:
    image: "docker.io/bitnami/postgresql:11"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - "postgresql_data:/bitnami/postgresql"
  keycloak-1:
    image: docker.io/bitnami/keycloak:latest
    ports:
      - "80:8080"
      - "8443:8443"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_JGROUPS_DISCOVERY_PROTOCOL=JDBC_PING
      - 'KEYCLOAK_JGROUPS_DISCOVERY_PROPERTIES=datasource_jndi_name=>java:jboss/datasources/KeycloakDS, initialize_sql=>"CREATE TABLE IF NOT EXISTS JGROUPSPING ( own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, created timestamp default current_timestamp, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name))"'
      - KEYCLOAK_CACHE_OWNERS_COUNT=3
      - KEYCLOAK_AUTH_CACHE_OWNERS_COUNT=3
    depends_on:
      - postgresql
volumes:
  postgresql_data:
    driver: local``

### Anything else?

https://github.com/bitnami/bitnami-docker-keycloak/issues/51

**Comment by stianst** [comment]
With Keycloak 20 the WildFly based distribution is no longer supported. For the newer Quarkus distribution of Keycloak, check out the [new documentation](https://www.keycloak.org/server/containers), or the [updated container sources](https://github.com/keycloak/keycloak/tree/main/quarkus/container).
