### ISSUE TITLE
v17.0.1 and v18.0.0 are missing on hub.docker.com

### ISSUE THREAD

**Issue by MrDeerly** [keycloak/keycloak-containers#399]
### Describe the bug

Hey,

it seems like the latest two version are missing on dockerhub. We already had that isse with an older version.. see: https://github.com/keycloak/keycloak-containers/issues/349

### Version

v17.0.1

**Comment by Writtscher** [comment]
Well I am glad that I am not the only one searching for the latest version.

I hope we will see the latest docker version anytime soon. 

@stianst Please help :)

**Comment by vvarga007** [comment]
You can find it on Quay.io.
https://quay.io/repository/keycloak/keycloak?tab=tags

**Comment by abstractj** [comment]
@Writtscher I will look into that

**Comment by Writtscher** [comment]
@abstractj Thank you.

**Comment by MrDeerly** [comment]
@abstractj thanks for looking into it. As this already happend a few times (as far as i can remember) it would be great to check the whole process of publishing to dockerhub.

**Comment by abstractj** [comment]
@MrDeerly @Writtscher a proposal to automated was submitted here https://github.com/keycloak/keycloak/pull/11987. Meanwhile, to unblock you both tags were manually pushed to https://hub.docker.com/r/keycloak/keycloak/tags.

It should not be considered the official repository yet, until I get the approval from @keycloak/kc-maintainers

**Comment by abstractj** [comment]
Resolved by https://github.com/keycloak/keycloak/issues/11986
