### ISSUE TITLE
Provide support for overwriting imported realms

### ISSUE THREAD

**Issue by SoccerBoyMalloy** [keycloak/keycloak-containers#400]
### Description

As outlined [here](https://github.com/keycloak/keycloak-containers/blob/29f9aa3e38d7b84d0baa0f0aa645cfb4ac729ab5/server/README.md#importing-a-realm), it's possible to import a realm. This works great until you need to overwrite an existing realm (like `master`). Doing so requires specifying the `keycloak.migration.strategy=OVERWRITE_EXISTING` parameter, which isn't directly possible with this image.

[This documentation](https://github.com/keycloak/keycloak-documentation/blob/main/server_admin/topics/export-import.adoc#importing-and-exporting-the-database) states:
>You cannot use the keycloak.import parameter with keycloak.migration.X parameters. If you use these parameters together, {project_name} ignores the keycloak.import parameter.

That means that in order to perform the overwrite I had to specify `KEYCLOAK_IMPORT`, [which turns into keycloak.import](https://github.com/keycloak/keycloak-containers/blob/53f4946b9add671f22c8ded6ec54415e8923ea0f/server/tools/docker-entrypoint.sh#L72), with a dummy value and then abuse it by tacking on the import options I actually want:
```
env:
  - name: KEYCLOAK_IMPORT
    value: "/opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.migration.strategy=OVERWRITE_EXISTING -Dkeycloak.profile.feature.upload_scripts=enabled"
```

In this case, the first `/opt/jboss/keycloak/imports/realm-export.json` gets completely ignored. It'd be nice if there was a better way to specify arbitrary `keycloak.migration.*` options.

**Comment by stianst** [comment]
With Keycloak 20 the WildFly based distribution is no longer supported. For the newer Quarkus distribution of Keycloak, check out the [new documentation](https://www.keycloak.org/server/containers), or the [updated container sources](https://github.com/keycloak/keycloak/tree/main/quarkus/container).
