### ISSUE TITLE
Make arm64-builds available on dockerhub

### ISSUE THREAD

**Issue by charma** [keycloak/keycloak-containers#405]
### Description

after lots of issues on my arm64 (macbook) I was able to find out that the docker-virtualisation to arm64 seems to have a problem to run other builds with java applications properly. I know that this issue has been fixed by providing arm64 builds on quay or using unofficial arm64-builds on dockerhub.
Anyways, it would be nice to have an official arm64 build on dockerhub too. It is already available so maybe its no big deal to publish it to dockerhub too?

I would highly appreciate it. Thank you!

### Motivation

docker on macbook/M1 chip (arm64 architecture) has problems running amd64 images with java application in virtualization on a arm64-platform.
known issue:
https://github.com/docker/for-mac/issues/5310
https://stackoverflow.com/questions/67044893/m1-mac-cannot-run-jboss-keycloak-docker-image

**Comment by punkratz312** [comment]
plz fix its frustrating to do this by hand....

**Comment by stianst** [comment]
With Keycloak 20 the WildFly based distribution is no longer supported. For the newer Quarkus distribution of Keycloak, check out the [new documentation](https://www.keycloak.org/server/containers), or the [updated container sources](https://github.com/keycloak/keycloak/tree/main/quarkus/container).
