### ISSUE TITLE
keycloak-init-container - "Extension downloaded successfully" with 0 bytes 

### ISSUE THREAD

**Issue by bszeti** [keycloak/keycloak-containers#418]
### Description

The keycloak-init-container was run to download an extension (KEYCLOAK_EXTENSIONS=https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.5.3/keycloak-metrics-spi-2.5.3.jar), but the download was incomplete. Despite the downloaded file was 0 bytes, the download was considered successful, so Keycloak container started despite the missing file.

The reason for the 0 byte download is unknown, the jar file is usually downloaded completely. In this case the http return code was probably 200, but then the Content was still empty (network or server side issue?). Is there a way to use "curl --fail" and verify the error code afterwards to check that the whole download was ok.

### Details

Issue was seen with SSO v7.5.2 (registry.redhat.io/rh-sso-7/sso7-rhel8-init-container@sha256:c0966b7320b0c9225402b1f3cefdb04be231c19919c4448eb4d404f690a1ea4e)

KEYCLOAK_EXTENSIONS=https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.5.3/keycloak-metrics-spi-2.5.3.jar 

Init container log:
```
Target directory: /opt/extensions 
Downloading extension from https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.5.3/keycloak-metrics-spi-2.5.3.jar 
Extension downloaded successfully 
--> keycloak-metrics-spi-2.5.3.jar 
All extensions downloaded successfully
```

Keycloak container:
```
sh-4.4$ ls -las /deployments/ 
total 4 
0 drwxrwsrwx. 2 root  1001050000  89 Jul  8 11:21 . 
0 dr-xr-xr-x. 1 root  root        76 Jul  8 11:20 .. 
0 -rw-r--r--. 1 jboss 1001050000   0 Jul  8 11:14 keycloak-metrics-spi-2.5.3.jar 
4 -rw-r--r--. 1 jboss 1001050000 413 Jul  8 11:21 keycloak-metrics-spi-2.5.3.jar.failed 
sh-4.4$ cat keycloak-metrics-spi-2.5.3.jar.failed  
"{\"WFLYCTL0080: Failed services\" => {\"jboss.deployment.unit.\\\"keycloak-metrics-spi-2.5.3.jar\\\".STRUCTURE\" => \"WFLYSRV0153: Failed to process phase STRUCTURE of deployment \\\"keycloak-metrics-spi-2.5.3.jar\\\" 
    Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYSRV0160: Failed to mount deployment content 
    Caused by: java.util.zip.ZipException: zip file is empty\"}}" 
```

**Comment by stianst** [comment]
With Keycloak 20 the WildFly based distribution is no longer supported. For the newer Quarkus distribution of Keycloak, check out the [new documentation](https://www.keycloak.org/server/containers), or the [updated container sources](https://github.com/keycloak/keycloak/tree/main/quarkus/container).
