### ISSUE TITLE
Expose administrative REST API & web console at separate port

### ISSUE THREAD

**Issue by eyujy** [keycloak/keycloak-containers#421]
### Describe the bug

For keycloak container deployment, how can I expose the administrative REST API and the web console on a separate port from non-administrative usage. Is there any env variables I can pass in when building/running the container?

Thank you!

### Version

18.0

**Comment by stianst** [comment]
With Keycloak 20 the WildFly based distribution is no longer supported. For the newer Quarkus distribution of Keycloak, check out the [new documentation](https://www.keycloak.org/server/containers), or the [updated container sources](https://github.com/keycloak/keycloak/tree/main/quarkus/container).
